name: Deploy Main
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-PROD-Action:
    name: FTP-Deploy-PROD-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-PROD-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER_PROD }}
        username: ${{ secrets.FTP_USER_PROD }}
        password: ${{ secrets.FTP_PWD_PROD }}
